/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vinci_dtp_ChamLib */

#ifndef _Included_com_vinci_dtp_ChamLib
#define _Included_com_vinci_dtp_ChamLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vinci_dtp_ChamLib
 * Method:    getScore
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_vinci_dtp_ChamLib_getScore
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
